import type { Database } from '@/lib/supabase/types';

/**
 * Domain types for the Recruiter MVP. This feature never re-derives an
 * assessment, a skill, or an evidence fact — everything it renders about a
 * candidate's work is read through `features/profile` (see
 * `server/service.ts`). Types here describe only what this feature adds:
 * the candidate list shape, sorting, and a recruiter's private tracking
 * state for one candidate.
 */

export type CandidateStatus = Database['public']['Enums']['candidate_status'];
export type AnalysisStatus = Database['public']['Enums']['analysis_status'];

export type CandidateListSort = 'recent' | 'alphabetical';

/** One row in the candidate list — deliberately thin, no ranking or score (spec: "No ranking. No AI sorting."). */
export interface CandidateListItem {
  readonly profileId: string;
  readonly name: string;
  /** Top assessed skill, e.g. "Strong — Backend Service Design"; null when nothing has been assessed yet. */
  readonly headline: string | null;
  readonly topSkills: readonly string[];
  readonly lastAnalyzedAt: string | null;
  readonly profileStatus: AnalysisStatus | 'no_analysis';
  readonly bookmarked: boolean;
  readonly status: CandidateStatus;
}

/** A recruiter's private tracking state for one candidate — absent (all defaults) until they first act. */
export interface CandidateTracking {
  readonly bookmarked: boolean;
  readonly status: CandidateStatus;
  /** Markdown, private to the recruiter. Never sent to or generated by the AI pipeline. */
  readonly note: string | null;
  readonly updatedAt: string | null;
}

export const DEFAULT_CANDIDATE_TRACKING: CandidateTracking = {
  bookmarked: false,
  status: 'new',
  note: null,
  updatedAt: null,
};
